[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."api"]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
